apiVersion: v2
name: foundry-vtt
description: Foundry Virtual Tabletop
type: application
version: 0.9.281
appVersion: "v9.280"
keywords:
  - game
  - server
  - vtt
  - virtualtabletop
  - foundryvtt
  - foundry
sources:
  - https://github.com/hugoprudente/charts/tree/main/incubator/foundry-vtt
maintainers:
  - name: hugoprudente
    email: hugo.kenshin@gmail.com
